<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.24">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Roberto Ramirez.">

<title>7&nbsp; Código Final de Curso Regreción Lineal – Porfolio</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../files/c1-bash.html" rel="next">
<link href="../files/c5-r.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-a37c72dd2dbac68997fcdc15a3622e78.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-485d01fc63b59abcd3ee1bf1e8e2748d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://hypothes.is/embed.js"></script>
<script>
  window.document.addEventListener("DOMContentLoaded", function (_event) {
    document.body.classList.add('hypothesis-enabled');
  });
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../files/c5-r.html">R</a></li><li class="breadcrumb-item"><a href="../files/Linear-Regression-in-R-for-Public-Health.html"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Código Final de Curso Regreción Lineal</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Porfolio</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Porfolio</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../files/front-matter.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">front-matter.html</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../files/c3-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Python</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../files/c4-python.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">python</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../files/01_the_machine_learning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Code example 1-1</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">R</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../files/c5-r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../files/Linear-Regression-in-R-for-Public-Health.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Código Final de Curso Regreción Lineal</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Bash</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../files/c1-bash.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Bash</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Javascript</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../files/c8-d3-graph3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">D3-graph3</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">D3</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../files/c8-d3-graph1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Graph1</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../files/c8-d3-graph2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Index-Graph-3D</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../files/c8-d3-graph3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">D3-graph3</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">HTML</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../files/c9-html-css.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Html-css</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../files/c9-html.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">HTML 1</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../files/c9-html2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Animacion and AWS</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../files/summary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Summary</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../files/glossary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Glosory</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../files/references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">References</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../files/colophon.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Colophon</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#r-markdown" id="toc-r-markdown" class="nav-link active" data-scroll-target="#r-markdown"><span class="header-section-number">7.1</span> R Markdown</a></li>
  <li><a href="#including-plots" id="toc-including-plots" class="nav-link" data-scroll-target="#including-plots"><span class="header-section-number">7.2</span> Including Plots</a></li>
  <li><a href="#final-r-code" id="toc-final-r-code" class="nav-link" data-scroll-target="#final-r-code"><span class="header-section-number">8</span> Final R Code</a>
  <ul class="collapse">
  <li><a href="#starting-r-and-opening-a-dataset" id="toc-starting-r-and-opening-a-dataset" class="nav-link" data-scroll-target="#starting-r-and-opening-a-dataset"><span class="header-section-number">8.1</span> Starting R and opening a dataset</a>
  <ul class="collapse">
  <li><a href="#new-r-script" id="toc-new-r-script" class="nav-link" data-scroll-target="#new-r-script"><span class="header-section-number">8.1.1</span> New R script</a></li>
  <li><a href="#install-a-new-package" id="toc-install-a-new-package" class="nav-link" data-scroll-target="#install-a-new-package"><span class="header-section-number">8.1.2</span> Install a new package</a></li>
  <li><a href="#viewing-the-dataset" id="toc-viewing-the-dataset" class="nav-link" data-scroll-target="#viewing-the-dataset"><span class="header-section-number">8.1.3</span> Viewing the dataset</a></li>
  <li><a href="#running-a-linear-regression" id="toc-running-a-linear-regression" class="nav-link" data-scroll-target="#running-a-linear-regression"><span class="header-section-number">8.1.4</span> Running a linear regression</a></li>
  <li><a href="#create-a-histogram" id="toc-create-a-histogram" class="nav-link" data-scroll-target="#create-a-histogram"><span class="header-section-number">8.1.5</span> Create a histogram</a></li>
  <li><a href="#summary-statistics" id="toc-summary-statistics" class="nav-link" data-scroll-target="#summary-statistics"><span class="header-section-number">8.1.6</span> Summary statistics</a></li>
  <li><a href="#correlation" id="toc-correlation" class="nav-link" data-scroll-target="#correlation"><span class="header-section-number">8.1.7</span> Correlation</a></li>
  <li><a href="#creating-a-correlation-matrix" id="toc-creating-a-correlation-matrix" class="nav-link" data-scroll-target="#creating-a-correlation-matrix"><span class="header-section-number">8.1.8</span> Creating a correlation matrix:</a></li>
  <li><a href="#multiple-linear-regression" id="toc-multiple-linear-regression" class="nav-link" data-scroll-target="#multiple-linear-regression"><span class="header-section-number">8.1.9</span> Multiple linear regression</a></li>
  <li><a href="#changing-data-type-for-a-variable" id="toc-changing-data-type-for-a-variable" class="nav-link" data-scroll-target="#changing-data-type-for-a-variable"><span class="header-section-number">8.1.10</span> Changing data type for a variable</a></li>
  <li><a href="#creating-a-new-variable-on-r-e.g.-variable-comorbid" id="toc-creating-a-new-variable-on-r-e.g.-variable-comorbid" class="nav-link" data-scroll-target="#creating-a-new-variable-on-r-e.g.-variable-comorbid"><span class="header-section-number">8.1.11</span> Creating a new variable on R: e.g.&nbsp;variable ‘comorbid’</a></li>
  <li><a href="#regression-with-interaction-effect" id="toc-regression-with-interaction-effect" class="nav-link" data-scroll-target="#regression-with-interaction-effect"><span class="header-section-number">8.1.12</span> Regression with interaction effect</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#week-1" id="toc-week-1" class="nav-link" data-scroll-target="#week-1"><span class="header-section-number">9</span> WEEK 1</a></li>
  <li><a href="#week-2" id="toc-week-2" class="nav-link" data-scroll-target="#week-2"><span class="header-section-number">10</span> WEEK 2</a>
  <ul class="collapse">
  <li><a href="#feedback-week-2" id="toc-feedback-week-2" class="nav-link" data-scroll-target="#feedback-week-2"><span class="header-section-number">10.0.1</span> Feedback Week 2</a></li>
  </ul></li>
  <li><a href="#week-3" id="toc-week-3" class="nav-link" data-scroll-target="#week-3"><span class="header-section-number">11</span> WEEK 3</a>
  <ul class="collapse">
  <li><a href="#introduction-to-key-dataset-features-part-i" id="toc-introduction-to-key-dataset-features-part-i" class="nav-link" data-scroll-target="#introduction-to-key-dataset-features-part-i"><span class="header-section-number">11.0.1</span> Introduction to Key Dataset Features: Part I</a></li>
  <li><a href="#introduction-to-key-dataset-features-part-i-1" id="toc-introduction-to-key-dataset-features-part-i-1" class="nav-link" data-scroll-target="#introduction-to-key-dataset-features-part-i-1"><span class="header-section-number">11.0.2</span> Introduction to Key Dataset Features: Part I</a></li>
  <li><a href="#how-to-assess-key-features-of-a-dataset-in-r" id="toc-how-to-assess-key-features-of-a-dataset-in-r" class="nav-link" data-scroll-target="#how-to-assess-key-features-of-a-dataset-in-r"><span class="header-section-number">11.0.3</span> How to assess key features of a dataset in R</a></li>
  <li><a href="#good-practice-steps" id="toc-good-practice-steps" class="nav-link" data-scroll-target="#good-practice-steps"><span class="header-section-number">11.0.4</span> Good Practice Steps</a></li>
  <li><a href="#practice-with-r-run-a-good-practice-analysis" id="toc-practice-with-r-run-a-good-practice-analysis" class="nav-link" data-scroll-target="#practice-with-r-run-a-good-practice-analysis"><span class="header-section-number">11.0.5</span> Practice with R: Run a Good Practice Analysis</a></li>
  <li><a href="#practice-with-r-run-multiple-regression" id="toc-practice-with-r-run-multiple-regression" class="nav-link" data-scroll-target="#practice-with-r-run-multiple-regression"><span class="header-section-number">11.0.6</span> Practice with R: Run Multiple Regression</a></li>
  <li><a href="#feedback-practice-with-r-run-multiple-regression" id="toc-feedback-practice-with-r-run-multiple-regression" class="nav-link" data-scroll-target="#feedback-practice-with-r-run-multiple-regression"><span class="header-section-number">11.0.7</span> Feedback Practice with R: Run Multiple Regression</a></li>
  </ul></li>
  <li><a href="#week-4" id="toc-week-4" class="nav-link" data-scroll-target="#week-4"><span class="header-section-number">12</span> WEEk 4</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../files/c5-r.html">R</a></li><li class="breadcrumb-item"><a href="../files/Linear-Regression-in-R-for-Public-Health.html"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Código Final de Curso Regreción Lineal</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Código Final de Curso Regreción Lineal</span></h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Roberto Ramirez. </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="r-markdown" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="r-markdown"><span class="header-section-number">7.1</span> R Markdown</h2>
<p>This is an R Markdown document. Markdown is a simple formatting syntax for authoring HTML, PDF, and MS Word documents. For more details on using R Markdown see <a href="http://rmarkdown.rstudio.com" class="uri">http://rmarkdown.rstudio.com</a>.</p>
<p>When you click the <strong>Knit</strong> button a document will be generated that includes both content as well as the output of any embedded R code chunks within the document. You can embed an R code chunk like this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">getwd</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "/Users/robertoramirezmartinez/Documents/1 COURSERA/C_Cursos RR/Quarto/book-porfoliov.1/files"</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.6
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.1     ✔ tibble    3.3.0
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.2.0     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co">#e &lt;- utils::read.csv("../datasets/COPD_dataset.csv")</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>e <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"../datasets/COPDdataset.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
Rows: 101 Columns: 24
── Column specification
──────────────────────────────────────────────────────── Delimiter: "," chr
(1): COPDSEVERITY dbl (23): ...1, ID, AGE, PackHistory, MWT1, MWT2, MWT1Best,
FEV1, FEV1PRED, ...
ℹ Use `spec()` to retrieve the full column specification for this data. ℹ
Specify the column types or set `show_col_types = FALSE` to quiet this message.
• `` -&gt; `...1`</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co">#e &lt;- readr::read_csv(COPDdataset.csv)</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="co">#summary(e)</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("Hmisc")</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="co">#library(Hmisc)</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(e)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      ...1           ID              AGE        PackHistory   
 Min.   :  1   Min.   :  1.00   Min.   :44.0   Min.   :  1.0  
 1st Qu.: 26   1st Qu.: 49.00   1st Qu.:65.0   1st Qu.: 20.0  
 Median : 51   Median : 87.00   Median :71.0   Median : 36.0  
 Mean   : 51   Mean   : 91.41   Mean   :70.1   Mean   : 39.7  
 3rd Qu.: 76   3rd Qu.:143.00   3rd Qu.:75.0   3rd Qu.: 54.0  
 Max.   :101   Max.   :169.00   Max.   :88.0   Max.   :109.0  
                                                              
 COPDSEVERITY            MWT1            MWT2          MWT1Best    
 Length:101         Min.   :120.0   Min.   :120.0   Min.   :120.0  
 Class :character   1st Qu.:300.0   1st Qu.:303.8   1st Qu.:303.8  
 Mode  :character   Median :419.0   Median :399.0   Median :420.0  
                    Mean   :385.9   Mean   :390.3   Mean   :399.1  
                    3rd Qu.:460.5   3rd Qu.:459.0   3rd Qu.:465.2  
                    Max.   :688.0   Max.   :699.0   Max.   :699.0  
                    NA's   :2       NA's   :1       NA's   :1      
      FEV1          FEV1PRED           FVC           FVCPRED      
 Min.   :0.450   Min.   :  3.29   Min.   :1.140   Min.   : 27.00  
 1st Qu.:1.100   1st Qu.: 42.00   1st Qu.:2.270   1st Qu.: 71.00  
 Median :1.600   Median : 60.00   Median :2.770   Median : 84.00  
 Mean   :1.604   Mean   : 58.53   Mean   :2.955   Mean   : 86.44  
 3rd Qu.:1.960   3rd Qu.: 75.00   3rd Qu.:3.630   3rd Qu.:103.00  
 Max.   :3.180   Max.   :102.00   Max.   :5.370   Max.   :132.00  
                                                                  
      CAT              HAD             SGRQ        AGEquartiles  
 Min.   :  3.00   Min.   : 0.00   Min.   : 2.00   Min.   :1.000  
 1st Qu.: 12.00   1st Qu.: 6.00   1st Qu.:28.41   1st Qu.:1.000  
 Median : 18.00   Median :10.00   Median :38.21   Median :3.000  
 Mean   : 19.34   Mean   :11.18   Mean   :40.19   Mean   :2.475  
 3rd Qu.: 24.00   3rd Qu.:15.00   3rd Qu.:55.23   3rd Qu.:3.000  
 Max.   :188.00   Max.   :56.20   Max.   :77.44   Max.   :4.000  
                                                                 
      copd           gender          smoking         Diabetes     
 Min.   :1.000   Min.   :0.0000   Min.   :1.000   Min.   :0.0000  
 1st Qu.:2.000   1st Qu.:0.0000   1st Qu.:2.000   1st Qu.:0.0000  
 Median :2.000   Median :1.0000   Median :2.000   Median :0.0000  
 Mean   :2.198   Mean   :0.6436   Mean   :1.842   Mean   :0.2079  
 3rd Qu.:3.000   3rd Qu.:1.0000   3rd Qu.:2.000   3rd Qu.:0.0000  
 Max.   :4.000   Max.   :1.0000   Max.   :2.000   Max.   :1.0000  
                                                                  
    muscular       hypertension      AtrialFib          IHD         
 Min.   :0.0000   Min.   :0.0000   Min.   :0.000   Min.   :0.00000  
 1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.000   1st Qu.:0.00000  
 Median :0.0000   Median :0.0000   Median :0.000   Median :0.00000  
 Mean   :0.1881   Mean   :0.1188   Mean   :0.198   Mean   :0.08911  
 3rd Qu.:0.0000   3rd Qu.:0.0000   3rd Qu.:0.000   3rd Qu.:0.00000  
 Max.   :1.0000   Max.   :1.0000   Max.   :1.000   Max.   :1.00000  
                                                                    </code></pre>
</div>
</div>
</section>
<section id="including-plots" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="including-plots"><span class="header-section-number">7.2</span> Including Plots</h2>
<p>You can also embed plots, for example:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Linear-Regression-in-R-for-Public-Health_files/figure-html/pressure-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Note that the <code>echo = FALSE</code> parameter was added to the code chunk to prevent printing of the R code that generated the plot.</p>
</section>
<section id="final-r-code" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Final R Code</h1>
<section id="starting-r-and-opening-a-dataset" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="starting-r-and-opening-a-dataset"><span class="header-section-number">8.1</span> Starting R and opening a dataset</h2>
<section id="new-r-script" class="level3" data-number="8.1.1">
<h3 data-number="8.1.1" class="anchored" data-anchor-id="new-r-script"><span class="header-section-number">8.1.1</span> New R script</h3>
<p>Remove previous variables: rm(list=ls())  Set the working directory:  setwd(“file_pathway”) Loading a dataset, labelling it ‘COPD’: COPD &lt;- read.csv(“COPD_student_dataset.csv”)</p>
</section>
<section id="install-a-new-package" class="level3" data-number="8.1.2">
<h3 data-number="8.1.2" class="anchored" data-anchor-id="install-a-new-package"><span class="header-section-number">8.1.2</span> Install a new package</h3>
<p>install.packages(“Package name”) library(Package name) install.packages(“Hmisc”) library(Hmisc)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages(“Hmisc”)</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="co">#library(Hmisc) </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="viewing-the-dataset" class="level3" data-number="8.1.3">
<h3 data-number="8.1.3" class="anchored" data-anchor-id="viewing-the-dataset"><span class="header-section-number">8.1.3</span> Viewing the dataset</h3>
<p>Look at the whole dataset: View(COPD)  Print the first few rows of your dataset: head(COPD)  See how many rows and columns you have in your dataset: dim(COPD)  Look at the different variables in the dataset: colnames(COPD) Look at all the values in a variable: print(variable) To visualise the structure of the data in a variable: str(variable) Look at a specific value (x) in a variable: variable[x]<br>
For continuous variables:</p>
<p>View number of values, missing values, mean and ranges using the describe() function from the ‘Hmisc’ package. For categorical variables:</p>
<p>View number of values, missing values, mean and ranges using the describe() function from the ‘Hmisc’ package OR Tabulate the data to view the number of values and their frequency using the CrossTable() function from the ’gmodels package. To view missing values, type: sum(is.na(variable)). Viewing the categories and distribution of entries in a categorical variable: table(catvariable) You can add the argument exclude = NULL in the function parentheses to include missing values in the output.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co">#View(e) </span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(e) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 24
   ...1    ID   AGE PackHistory COPDSEVERITY  MWT1  MWT2 MWT1Best  FEV1 FEV1PRED
  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;       &lt;dbl&gt; &lt;chr&gt;        &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;
1     1    58    77          60 SEVERE         120   120      120  1.21       36
2     2    57    79          50 MODERATE       165   176      176  1.09       56
3     3    62    80          11 MODERATE       201   180      201  1.52       68
4     4   145    56          60 VERY SEVERE    210   210      210  0.47       14
5     5   136    65          68 SEVERE         204   210      210  1.07       42
6     6    84    67          26 MODERATE       216   180      216  1.09       50
# ℹ 14 more variables: FVC &lt;dbl&gt;, FVCPRED &lt;dbl&gt;, CAT &lt;dbl&gt;, HAD &lt;dbl&gt;,
#   SGRQ &lt;dbl&gt;, AGEquartiles &lt;dbl&gt;, copd &lt;dbl&gt;, gender &lt;dbl&gt;, smoking &lt;dbl&gt;,
#   Diabetes &lt;dbl&gt;, muscular &lt;dbl&gt;, hypertension &lt;dbl&gt;, AtrialFib &lt;dbl&gt;,
#   IHD &lt;dbl&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(e) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 101  24</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(e) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "...1"         "ID"           "AGE"          "PackHistory"  "COPDSEVERITY"
 [6] "MWT1"         "MWT2"         "MWT1Best"     "FEV1"         "FEV1PRED"    
[11] "FVC"          "FVCPRED"      "CAT"          "HAD"          "SGRQ"        
[16] "AGEquartiles" "copd"         "gender"       "smoking"      "Diabetes"    
[21] "muscular"     "hypertension" "AtrialFib"    "IHD"         </code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(e<span class="sc">$</span>AGE) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1] 77 79 80 56 65 67 67 83 72 75 76 59 64 74 70 71 69 55 72 72 74 75 69 73 75
 [26] 80 76 73 77 88 44 82 73 64 76 83 65 74 70 71 78 75 67 78 73 53 64 81 82 71
 [51] 65 71 78 73 72 63 60 75 73 66 80 81 73 71 69 74 62 68 70 67 70 49 75 73 78
 [76] 67 75 76 63 65 65 62 63 64 72 61 60 78 67 68 72 69 68 52 55 72 68 75 68 54
[101] 78</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(e<span class="sc">$</span>AGE) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> num [1:101] 77 79 80 56 65 67 67 83 72 75 ...</code></pre>
</div>
</div>
</section>
<section id="running-a-linear-regression" class="level3" data-number="8.1.4">
<h3 data-number="8.1.4" class="anchored" data-anchor-id="running-a-linear-regression"><span class="header-section-number">8.1.4</span> Running a linear regression</h3>
<p>The basic format is:</p>
<p>modelname &lt;- lm(outcome~predictor, data = dataframe) Viewing the regression model output: summary(modelname) Viewing the model 95% confidence intervals: confint(modelname) Drawing a Q-Q plot, constant variance plot, and other diagnostic plots</p>
<p>Calculate predicted values: predict(modelname) Calculate residuals: residuals(modelname) Set a plotting format of 4 graphs: par(mfrow=c(2,2))  View the 4 resulting plots: plot(modelname)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>MWT1Best_edad <span class="ot">&lt;-</span> <span class="fu">lm</span>(e<span class="sc">$</span>MWT1Best<span class="sc">~</span>e<span class="sc">$</span>AGE, <span class="at">datos =</span> e) <span class="co">#1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: In lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...) :
 extra argument 'datos' will be disregarded</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(MWT1Best_edad) <span class="co">#2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = e$MWT1Best ~ e$AGE, datos = e)

Residuals:
    Min      1Q  Median      3Q     Max 
-257.44  -84.40   20.30   67.87  250.16 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  616.453     93.440   6.597 2.14e-09 ***
e$AGE         -3.104      1.326  -2.341   0.0213 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 104.2 on 98 degrees of freedom
  (1 observation deleted due to missingness)
Multiple R-squared:  0.05294,   Adjusted R-squared:  0.04328 
F-statistic: 5.478 on 1 and 98 DF,  p-value: 0.02128</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(MWT1Best_edad) <span class="co">#3</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 2.5 %      97.5 %
(Intercept) 431.023080 801.8819906
e$AGE        -5.735718  -0.4722946</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>MWT1Best_gender <span class="ot">&lt;-</span> <span class="fu">lm</span>(e<span class="sc">$</span>MWT1Best<span class="sc">~</span>e<span class="sc">$</span>gender, <span class="at">datos =</span> e) <span class="co">#1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: In lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...) :
 extra argument 'datos' will be disregarded</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(MWT1Best_gender) <span class="co">#2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = e$MWT1Best ~ e$gender, datos = e)

Residuals:
    Min      1Q  Median      3Q     Max 
-290.09  -87.96   18.66   74.92  288.91 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   379.58      17.68  21.473   &lt;2e-16 ***
e$gender       30.51      22.10   1.381     0.17    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 106.1 on 98 degrees of freedom
  (1 observation deleted due to missingness)
Multiple R-squared:  0.01908,   Adjusted R-squared:  0.009073 
F-statistic: 1.906 on 1 and 98 DF,  p-value: 0.1705</code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(MWT1Best_gender) <span class="co">#3</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                2.5 %    97.5 %
(Intercept) 344.50270 414.66397
e$gender    -13.34038  74.36121</code></pre>
</div>
</div>
</section>
<section id="create-a-histogram" class="level3" data-number="8.1.5">
<h3 data-number="8.1.5" class="anchored" data-anchor-id="create-a-histogram"><span class="header-section-number">8.1.5</span> Create a histogram</h3>
<p>The basic format is: hist(variablename) If you are getting a variable from the dataset, the $ sign allows R to locate this variable. E.g. COPD$MWT1Best To change the title of the histogram, use the command: main = “histogram title” Don’t forget quotation marks when using text! To change the x or y axes labels, use the commands: xlab = “x axis label” or ylab = “y axis label” Don’t forget quotation marks using text! To change the number of bins displayed, use the command main = to specify the number of bins you want to see. To look at specific values in your variable, you can use the subset() function, using the basic code subset(dataframe, variable &gt; 15) if you want to see values over 15 for that variable. You can add additive rules by including ‘|’, e.g.&nbsp;subset(dataframe, variable1 &gt; 15 | variable2 &lt; 5)</p>
</section>
<section id="summary-statistics" class="level3" data-number="8.1.6">
<h3 data-number="8.1.6" class="anchored" data-anchor-id="summary-statistics"><span class="header-section-number">8.1.6</span> Summary statistics</h3>
<p>Basic summary statistics (incl.&nbsp;minimum, medium, maximum, 1st and 3rd quartiles, and number of blank cells): summary(variablename) List of summary statistics, including the basic summary() outcome, standard deviation, range, and inter-quartile range:<br>
list(summary(variablename), sd(variablename, na.rm = TRUE), range(variablename, na.rm = TRUE), IQR(variablename, na.rm = TRUE)) Note that the na.rm = TRUE command tells R to remove NA values. Without this, an error message will be displayed.</p>
</section>
<section id="correlation" class="level3" data-number="8.1.7">
<h3 data-number="8.1.7" class="anchored" data-anchor-id="correlation"><span class="header-section-number">8.1.7</span> Correlation</h3>
<p>Scatterplot of two variables: plot(x, y) Correlation coefficient: cor(x, y) The default method is Pearson, but you can change this to Spearman by adding method = “spearman” in your parentheses. You need to remove missing values, otherwise you will get an error message. To do this, add use = “complete.obs” in your parentheses. Correlation test: cor.test(x, y) The default method is also Pearson here. You also need to remove missing values to avoid an error message.</p>
</section>
<section id="creating-a-correlation-matrix" class="level3" data-number="8.1.8">
<h3 data-number="8.1.8" class="anchored" data-anchor-id="creating-a-correlation-matrix"><span class="header-section-number">8.1.8</span> Creating a correlation matrix:</h3>
<p>Create a vector with the variables to include in the matrix, e.g.&nbsp;data &lt;- COPD[,c(“AGE”, “PackHistory”, “FEV1”)] Create the correlation matrix vector, assigning correlation coefficients of the different variables to it, e.g.&nbsp;cor_matrix &lt;- cor(data) View the matrix: e.g.&nbsp;cor_matrix to view the output and round(cor_matrix,2) to round this output to 2 decimal points. Visualising correlation between variables, i.e.&nbsp;correlation plot: pairs(~ variable1 + variable2 + variable3, data = dataframe)</p>
</section>
<section id="multiple-linear-regression" class="level3" data-number="8.1.9">
<h3 data-number="8.1.9" class="anchored" data-anchor-id="multiple-linear-regression"><span class="header-section-number">8.1.9</span> Multiple linear regression</h3>
<p>The basic format is:</p>
<p>modelname &lt;- lm(outcome~predictor1 + predictor2, data = dataframe) Viewing the regression model output: summary(modelname) Viewing the model 95% confidence intervals: confint(modelname) Examining the VIF using the imcdiagF() function from the ‘mctest’ package. Regression with categorical variables</p>
<p>2 ways to do this:</p>
<p>Check what the variable is saved as, change it to a factor variable if it is not saved as such. Check what the variable has been saved as using the class() function If it is not saved as a factor, can it using the factor() command, in the following format: variable &lt;- factor(variable) Run the regression as normal Include factor() before the variable in the regression model. E.g. modelname &lt;- lm(outcome~predictor1 + factor(predictor2), data = dataframe) Changing the reference category of a variable:</p>
<p>Use the relevel() function in the following format: variable &lt;- relevel(variable, ref = newreflevel) with the newreflevel being the new reference level, written either as a numeric (1, 2, 3, …) or a character (in which case it needs to be written within apostrophes – “MILD”, “SEVERE”, …)</p>
</section>
<section id="changing-data-type-for-a-variable" class="level3" data-number="8.1.10">
<h3 data-number="8.1.10" class="anchored" data-anchor-id="changing-data-type-for-a-variable"><span class="header-section-number">8.1.10</span> Changing data type for a variable</h3>
<p>Check what the variable has been as using the class() function. Changing data type: To numeric: as.numeric() To character: as.character() To factor: factor() or as.factor() To integer: as.integer()</p>
</section>
<section id="creating-a-new-variable-on-r-e.g.-variable-comorbid" class="level3" data-number="8.1.11">
<h3 data-number="8.1.11" class="anchored" data-anchor-id="creating-a-new-variable-on-r-e.g.-variable-comorbid"><span class="header-section-number">8.1.11</span> Creating a new variable on R: e.g.&nbsp;variable ‘comorbid’</h3>
<p>comorbid is a variable you were asked to create. This variable was to be binary, and indicated the presence of at least one comorbidity (‘1’) or complete absence of comorbidities (‘0’) based on the responses to the variables: Diabetes, muscular, hypertension, AtrialFib, and IHD. </p>
<p>Check that all variables are saved as the correct datatype. Create an empty vector of the correct length. Here, comorbid will be the same length as the other variables, so: comorbid &lt;- length(COPD<span class="math inline">\(Diabetes)
Assign values to this vector.
Here, we want comorbid = 1 when Diabetes OR muscular OR hypertension OR AtrialFib OR IHD = 1. So: comorbid[COPD\)</span>Diabetes == 1 | COPD<span class="math inline">\(muscular == 1 | COPD\)</span>hypertension == 1 | COPD<span class="math inline">\(AtrialFib == 1 | COPD\)</span>IHD == 1] &lt;- 1<br>
This will assign 1 to the values meeting the set conditions, and NAs to those that are not meeting those conditions. We also want comorbid = 0 when ALL above variables = 0. So: comorbid[is.na(cormorbid)] &lt;- 0 Convert this variable to a factor. Optional: add the variable to the dataset, using the following command COPD$comorbid &lt;- cormorbid</p>
</section>
<section id="regression-with-interaction-effect" class="level3" data-number="8.1.12">
<h3 data-number="8.1.12" class="anchored" data-anchor-id="regression-with-interaction-effect"><span class="header-section-number">8.1.12</span> Regression with interaction effect</h3>
<p>Use the same format as a multiple linear regression, but include both terms, i.e.&nbsp;modelname &lt;- lm(outcome~predictor1 + predictor2 + (predictor1 * predictor2),<br>
data = dataframe) Interpretation of the interaction effect can be simplified using the prediction() function from the ‘prediction’ package.</p>
</section>
</section>
</section>
<section id="week-1" class="level1" data-number="9">
<h1 data-number="9"><span class="header-section-number">9</span> WEEK 1</h1>
</section>
<section id="week-2" class="level1" data-number="10">
<h1 data-number="10"><span class="header-section-number">10</span> WEEK 2</h1>
<section id="feedback-week-2" class="level3" data-number="10.0.1">
<h3 data-number="10.0.1" class="anchored" data-anchor-id="feedback-week-2"><span class="header-section-number">10.0.1</span> Feedback Week 2</h3>
<p>Feedback The first step is to produce the simple linear regression model between MWT1best and FVC. In R the code is:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>lr1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(MWT1Best<span class="sc">~</span>FVC, <span class="at">data =</span> e)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lr1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = MWT1Best ~ FVC, data = e)

Residuals:
     Min       1Q   Median       3Q      Max 
-251.663  -66.598    6.364   63.539  246.125 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  254.951     30.779   8.283 6.28e-13 ***
FVC           48.630      9.866   4.929 3.37e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 95.87 on 98 degrees of freedom
  (1 observation deleted due to missingness)
Multiple R-squared:  0.1987,    Adjusted R-squared:  0.1905 
F-statistic: 24.29 on 1 and 98 DF,  p-value: 3.368e-06</code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(lr1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                2.5 %    97.5 %
(Intercept) 193.87101 316.03072
FVC          29.05061  68.20964</code></pre>
</div>
</div>
<p>lr1 &lt;- lm(MWT1Best~FVC, data = COPD) # Run the regression, assigning the output to a new variable lr</p>
<p>summary(lr1) # View the output of the regression</p>
<p>confint(lr1) # View the 95% confidence intervals of the regression</p>
<p>N.B. The text following the # sign are comments to describe what the command is doing. It has no effect on the output. </p>
<p>This produces the following output:</p>
<p>undefined</p>
<p>This has fitted the following model:</p>
<p>MWT1best= α+β∗FVC</p>
<p>where</p>
<p>α = 254.95 and β=48.63 and adjusted R2 = 0.19.</p>
<p>You should have already fitted the model between MWT1best and AGE and found the following: lr2 &lt;- lm(MWT1Best~AGE, data = COPD)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>lr2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(MWT1Best<span class="sc">~</span>AGE, <span class="at">data =</span> e)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lr2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = MWT1Best ~ AGE, data = e)

Residuals:
    Min      1Q  Median      3Q     Max 
-257.44  -84.40   20.30   67.87  250.16 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  616.453     93.440   6.597 2.14e-09 ***
AGE           -3.104      1.326  -2.341   0.0213 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 104.2 on 98 degrees of freedom
  (1 observation deleted due to missingness)
Multiple R-squared:  0.05294,   Adjusted R-squared:  0.04328 
F-statistic: 5.478 on 1 and 98 DF,  p-value: 0.02128</code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(lr2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 2.5 %      97.5 %
(Intercept) 431.023080 801.8819906
AGE          -5.735718  -0.4722946</code></pre>
</div>
</div>
<p>summary(lr2)</p>
<p>confint(lr2)</p>
<p>undefined where</p>
<p>α = 616.45 and β=−3.10, and adjusted R2 = 0.04.</p>
<p>Once you know how to fit a simple linear regression model it should be straightforward fitting the multiple linear regression model. To do this in R you issue the follow command:</p>
<p>lr3 &lt;- lm(MWT1Best~FVC+AGE, data = COPD)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>lr3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(MWT1Best<span class="sc">~</span>FVC<span class="sc">+</span>AGE, <span class="at">data =</span> e) </span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lr3) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = MWT1Best ~ FVC + AGE, data = e)

Residuals:
    Min      1Q  Median      3Q     Max 
-236.89  -66.05   12.55   75.54  211.72 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  425.377     94.099   4.521 1.74e-05 ***
FVC           46.058      9.827   4.687 9.06e-06 ***
AGE           -2.325      1.215  -1.914   0.0586 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 94.59 on 97 degrees of freedom
  (1 observation deleted due to missingness)
Multiple R-squared:  0.2278,    Adjusted R-squared:  0.2119 
F-statistic: 14.31 on 2 and 97 DF,  p-value: 3.588e-06</code></pre>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(lr3) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 2.5 %       97.5 %
(Intercept) 238.616666 612.13818023
FVC          26.553107  65.56260023
AGE          -4.736637   0.08649919</code></pre>
</div>
</div>
<p>summary(lr3)</p>
<p>confint(lr3)</p>
<p>undefined This has fitted the following model:</p>
<p>MWT1best= α+β1∗FVC+ β2∗AGE</p>
<p>where α = 425.38, β1=46.06 and β2 = -2.33.</p>
<p>Comparing the output from the multiple regression model with the two models with single predictor variables you can see that both coefficients have slightly reduced in the multiple regression model.</p>
<p>The FVC coefficient has reduced from 48.6 to 46.1, and the AGE coefficient has reduced from -3.1 to -2.3. You might have also noticed that the p-value for FVC remains small (&lt;0.001) but the p-value for AGE has increased to 0.059. Remember, this change is because the coefficients are now adjusted coefficients:</p>
<p>α is the estimated walking distance you would expect for people aged 0 years and with a FVC value of 0.</p>
<p>β1 is the average increase in walking distance for every one unit increase in FVC, keeping age held constant.</p>
<p>β2 is the average increase in walking distance for every one year increase in age, keeping FVC held constant.</p>
<p>Comparing the adjusted-R2 statistics you can see that the multivariable model now explains 21% of variance in the data compared with 19% for the model with FVC and 4% for the model with AGE.</p>
<p>Whilst the adjusted R2 statistic is marginally higher in this model with both FVC and AGE compared with the model with just FVC, you might question the inclusion of AGE given the p-value of 0.059, which does not allow you to reject the null hypothesis that the coefficient is 0 at the usual 5% significance threshold. Put that thought on hold for now. You’ll cover model development and variable selection later in the course and you will see that this should not solely rely on significance testing.</p>
<p>Your model doesn’t seem to show any indication of collinearity (remember that this is when there is a strong linear relationship between predictors that causes problems in estimation of model parameters). You can check this by examining the scatterplot or calculating a correlation coefficient such as Pearson’s or Spearman’s when there are only two predictors. However, this is not possible when the number of predictors increases beyond two. In that situation, you will need to produce a correlation matrix or calculate the Variance Inflation Factor (VIF), both of which will be covered later in the course.</p>
<p>Looking at the scatterplot between AGE and FVC you should see a fairly random scatter of points like below:</p>
<p>plot(COPD<span class="math inline">\(AGE, COPD\)</span>FVC, xlab =“AGE”, ylab =“FVC”)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(e<span class="sc">$</span>AGE, e<span class="sc">$</span>FVC, <span class="at">xlab =</span><span class="st">"AGE"</span>, <span class="at">ylab =</span><span class="st">"FVC"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Linear-Regression-in-R-for-Public-Health_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>undefined Calculating the Spearman’s correlation you should get -0.18. Therefore, there is only a very weak association between AGE and FVC, so collinearity is unlikely to be an issue. This is obtained by issuing the following command in R:</p>
<p>cor.test(COPD<span class="math inline">\(AGE, COPD\)</span>FVC, use=“complete.obs”, method=“spearman”)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(e<span class="sc">$</span>AGE, e<span class="sc">$</span>FVC, <span class="at">use=</span><span class="st">"complete.obs"</span>, <span class="at">method=</span><span class="st">"spearman"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in cor.test.default(e$AGE, e$FVC, use = "complete.obs", method =
"spearman"): Cannot compute exact p-value with ties</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Spearman's rank correlation rho

data:  e$AGE and e$FVC
S = 202110, p-value = 0.07642
alternative hypothesis: true rho is not equal to 0
sample estimates:
       rho 
-0.1771108 </code></pre>
</div>
</div>
<p>So, now that you’re satisfied that collinearity is not a problem, you need to check the other model assumptions.</p>
<p>Hopefully, you recalled that these are: 1) there is linearity between the outcome and predictor variables; (2) that the outcome variable is normally distributed across values of the predictors; and (3) that the variance of the outcome variable is constant across values of the predictor variables. Even with multiple predictors, if these assumptions are satisfied then the residuals (distance between the observed values and the fitted regression line) follow a normal distribution with mean zero and constant variance across the predictor values:</p>
<p>Residuals ~ Normal (0, σ2)</p>
<p>You can assess this by examining the appropriate plots.</p>
<p>Imagine you fit the following model:</p>
<p>MWT1best= α+β1∗FVC+ β2∗AGE+ β3 ∗FEV1</p>
<p>Can you think why this might not be a good idea?</p>
<p>FVC and FEV1 are both measures of lung function. Have a go and see what you get.</p>
</section>
</section>
<section id="week-3" class="level1" data-number="11">
<h1 data-number="11"><span class="header-section-number">11</span> WEEK 3</h1>
<section id="introduction-to-key-dataset-features-part-i" class="level3" data-number="11.0.1">
<h3 data-number="11.0.1" class="anchored" data-anchor-id="introduction-to-key-dataset-features-part-i"><span class="header-section-number">11.0.1</span> Introduction to Key Dataset Features: Part I</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>MWT1Best_gender<span class="ot">&lt;-</span> <span class="fu">lm</span>(e<span class="sc">$</span>MWT1Best<span class="sc">~</span>e<span class="sc">$</span>gender, <span class="at">data =</span> e) </span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(MWT1Best_gender) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = e$MWT1Best ~ e$gender, data = e)

Residuals:
    Min      1Q  Median      3Q     Max 
-290.09  -87.96   18.66   74.92  288.91 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   379.58      17.68  21.473   &lt;2e-16 ***
e$gender       30.51      22.10   1.381     0.17    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 106.1 on 98 degrees of freedom
  (1 observation deleted due to missingness)
Multiple R-squared:  0.01908,   Adjusted R-squared:  0.009073 
F-statistic: 1.906 on 1 and 98 DF,  p-value: 0.1705</code></pre>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(MWT1Best_gender) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                2.5 %    97.5 %
(Intercept) 344.50270 414.66397
e$gender    -13.34038  74.36121</code></pre>
</div>
</div>
<p>MWT1Best_gender = 379.7+ 30.5<em>Gender The regression coefficient for “gender” represents the expected chance in our outcome, “walking distance”, for a one unit increase in our predictor. Predicted mean in males. MWT1Best_gender = 379.7+ 30.5</em>1 = 410.1 Predicted mean in females. MWT1Best_gender = 379.7+ 30.5*0= 379.7</p>
</section>
<section id="introduction-to-key-dataset-features-part-i-1" class="level3" data-number="11.0.2">
<h3 data-number="11.0.2" class="anchored" data-anchor-id="introduction-to-key-dataset-features-part-i-1"><span class="header-section-number">11.0.2</span> Introduction to Key Dataset Features: Part I</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>w <span class="ot">&lt;-</span> <span class="fu">table</span>(e<span class="sc">$</span>COPDSEVERITY)</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>w</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
       MILD    MODERATE      SEVERE VERY SEVERE 
         23          43          27           8 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>t <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(w)</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>t</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         Var1 Freq
1        MILD   23
2    MODERATE   43
3      SEVERE   27
4 VERY SEVERE    8</code></pre>
</div>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>MWT1Best_COPDSEVERITY<span class="ot">&lt;-</span> <span class="fu">lm</span>(e<span class="sc">$</span>MWT1Best<span class="sc">~</span>e<span class="sc">$</span>COPDSEVERITY, <span class="at">data =</span> e) </span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(MWT1Best_COPDSEVERITY) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = e$MWT1Best ~ e$COPDSEVERITY, data = e)

Residuals:
    Min      1Q  Median      3Q     Max 
-248.67  -51.18    0.91   64.23  330.33 

Coefficients:
                          Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                 458.09      20.44  22.410  &lt; 2e-16 ***
e$COPDSEVERITYMODERATE      -51.09      25.43  -2.009  0.04735 *  
e$COPDSEVERITYSEVERE        -89.42      27.82  -3.215  0.00178 ** 
e$COPDSEVERITYVERY SEVERE  -167.21      40.24  -4.156 7.05e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 98.03 on 96 degrees of freedom
  (1 observation deleted due to missingness)
Multiple R-squared:  0.1792,    Adjusted R-squared:  0.1535 
F-statistic: 6.984 on 3 and 96 DF,  p-value: 0.0002671</code></pre>
</div>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(MWT1Best_COPDSEVERITY) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                              2.5 %      97.5 %
(Intercept)                417.5118 498.6621125
e$COPDSEVERITYMODERATE    -101.5638  -0.6101082
e$COPDSEVERITYSEVERE      -144.6361 -34.2044964
e$COPDSEVERITYVERY SEVERE -247.0842 -87.3396822</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>The regression coefficients here show how much walking distance changes for moderate, severe and very severe, all compared to mild disease. The coefficients are all negative, suggesting that walking distance decreases as disease severity increases, and the magnitude increases with increasing severity.</p>
</blockquote>
</section>
<section id="how-to-assess-key-features-of-a-dataset-in-r" class="level3" data-number="11.0.3">
<h3 data-number="11.0.3" class="anchored" data-anchor-id="how-to-assess-key-features-of-a-dataset-in-r"><span class="header-section-number">11.0.3</span> How to assess key features of a dataset in R</h3>
<p>When handed a new data set, before you do any analysis or model fit, you must always get to know and inspect your data! The main things you should be doing are:</p>
<ol type="1">
<li>Understanding your variables</li>
</ol>
<p>What type of variable are they? What are the ranges of each variable? What distributions do they follow? 2. Checking that the variables are in the correct format when imported into R</p>
<ol start="3" type="1">
<li>Inspecting to see if you have any missing data</li>
</ol>
<p>Getting to know your data set</p>
<p>You can see how many row and columns you have in your data set with the following command:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(e)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 101  24</code></pre>
</div>
</div>
<p>R gives the number of rows and columns, in that order. There are 101 rows (patients) and 24 columns (variables).</p>
<p>Let’s now look at what variables there are. You could do this by printing out the whole data set by simply typing COPD, but as it’s quite large and will clutter the R console, instead just print the first few rows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(e)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 24
   ...1    ID   AGE PackHistory COPDSEVERITY  MWT1  MWT2 MWT1Best  FEV1 FEV1PRED
  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;       &lt;dbl&gt; &lt;chr&gt;        &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;
1     1    58    77          60 SEVERE         120   120      120  1.21       36
2     2    57    79          50 MODERATE       165   176      176  1.09       56
3     3    62    80          11 MODERATE       201   180      201  1.52       68
4     4   145    56          60 VERY SEVERE    210   210      210  0.47       14
5     5   136    65          68 SEVERE         204   210      210  1.07       42
6     6    84    67          26 MODERATE       216   180      216  1.09       50
# ℹ 14 more variables: FVC &lt;dbl&gt;, FVCPRED &lt;dbl&gt;, CAT &lt;dbl&gt;, HAD &lt;dbl&gt;,
#   SGRQ &lt;dbl&gt;, AGEquartiles &lt;dbl&gt;, copd &lt;dbl&gt;, gender &lt;dbl&gt;, smoking &lt;dbl&gt;,
#   Diabetes &lt;dbl&gt;, muscular &lt;dbl&gt;, hypertension &lt;dbl&gt;, AtrialFib &lt;dbl&gt;,
#   IHD &lt;dbl&gt;</code></pre>
</div>
</div>
<p>It looks like a good mix of variable types: continuous, binary, categorical.</p>
<p><strong>Getting to know your variables</strong></p>
<p>It’s very important to inspect each variable individually, especially, those which you think you will use in your analyses!</p>
<p>In this exercise, you will learn how to do this for each variable type. Start with a continuous variable, age:</p>
<p>First - check the variable type with the command <strong>class():</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="co">#class(e$AGE)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>R tells you it is an “integer” variable. Technically, age is a continuous variable, but patient age is recorded to the year in the data set. This is OK for your purposes - R will treat this variable as a continuous one, unless you tell it otherwise.</p>
<p>The <strong>summary()</strong>command gives a summary of the age variable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="co">#summary(e$AGE)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The median age of the patient sample is 71 years, the youngest is 44 and the highest is 88. This command would also tell you if there are any missing values; you do not have any here.</p>
<p>The median and mean values are closer to the max value, which would suggest a negative skew.</p>
<p>You can graphically look at the distribution of ages with the **hist()* command:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(e<span class="sc">$</span>AGE)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "numeric"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(e<span class="sc">$</span>AGE)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   44.0    65.0    71.0    70.1    75.0    88.0 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(e<span class="sc">$</span>AGE)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Linear-Regression-in-R-for-Public-Health_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>There does indeed seem to be a slight negative skew to our patient ages: the tail at the lower end is longer than the tail at the upper end.</p>
<p>The same set of commands can be used for other continuous variables, like so with CAT score CAT:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(e<span class="sc">$</span>CAT)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "numeric"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(e<span class="sc">$</span>CAT)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   3.00   12.00   18.00   19.34   24.00  188.00 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(e<span class="sc">$</span>CAT)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Linear-Regression-in-R-for-Public-Health_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Both the <strong>summary()</strong> and <strong>hist()</strong> commands reveal something strange about the entries in this variable. There is an outlier here, at 188. In fact, CAT scores can only be between 0 and 40, so there is a mistake in your data set. Real life data sets are often full of mistakes; it is, therefore, important to spot these errors early and make decisions before you start your analyses.</p>
<p>Next, you will inspect a categorical variable, <strong>COPDSEVERITY</strong>. Check that it is in the right format:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(e<span class="sc">$</span>COPDSEVERITY)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "character"</code></pre>
</div>
</div>
<p>COPDSEVERITY is in the “factor” format which is the way R treats categorical data.</p>
<p>Now, you can have a look at the distribution of entries, using the table() command to do so.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(e<span class="sc">$</span>COPDSEVERITY, <span class="at">exclude =</span> <span class="cn">NULL</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
       MILD    MODERATE      SEVERE VERY SEVERE 
         23          43          27           8 </code></pre>
</div>
</div>
<p>Including the argument exclude = NULL asks R to include missing values in the output. For this variable, you have no missing values. you do have more patients in the ‘MODERATE’ category than any of the others.</p>
<p>Binary variables are treated similarly to categorical variables. R will by default treat variables with numbers as integers, so it’s good practice to make sure R knows that a variable is meant to be categorical with the following procedure.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(e<span class="sc">$</span>gender) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "numeric"</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>e<span class="sc">$</span>gender <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(e<span class="sc">$</span>gender) </span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(e<span class="sc">$</span>gender) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "factor"</code></pre>
</div>
</div>
<p>Now, gender is registered as a categorical variable and will be treated properly in any models you create. You can see the distribution of gender in the same way as any other categorical variable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(e<span class="sc">$</span>gender, <span class="at">exclude =</span> <span class="cn">NULL</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 0  1 
36 65 </code></pre>
</div>
</div>
<p>As mentioned before, these basic inspections must be performed before you jump into any analyses!</p>
<p>So, you now have the tools to perform all inspections necessary for all of the variables in this data set.<br>
### How to check your data in R</p>
<p>Checking what type of data R saved the variable as:</p>
<p>Open RStudio and load your dataset To check what type of data the different variables have been saved as, you can use the class() function The most common types of data are: Numeric—-Decimal values Integer—Numeric value with no fraction Character–Text/String variables, enclosed by apostrophes Logical —Objects (TRUE or FALSE) that encode a logic Factor —Categorical/nominal variables, with levels of data</p>
<p>So, for example, if you look at some of the variables in the COPD dataset, you will see that:</p>
<p>AGE is saved as an integer variable SGRQ is saved as a numeric variable COPDSEVERITY is saved as a factor variable, with 4 levels: mild, moderate, severe, very severe</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(e<span class="sc">$</span>AGE)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "numeric"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(e<span class="sc">$</span>SGRQ)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "numeric"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(e<span class="sc">$</span>COPDSEVERITY)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "character"</code></pre>
</div>
</div>
<p>Changing data type for a variable</p>
<ul>
<li>Let’s say you want to run the following regression: <strong>MWT1Best= α+ β∗copd</strong></li>
</ul>
<p>With your outcome variable, MWT1Best, being a numerical variable and your predictor variable, copd, a categorical variable with 4 levels.</p>
<ul>
<li>Check whether these variables are recorded correctly in R, using the commands:</li>
</ul>
<p><strong>class(COPD$MWT1Best)</strong></p>
<p><strong>class(COPD$copd)</strong></p>
<ul>
<li>The output shows that both variables are saved as integers. However, only <strong>MWT1Best</strong> should be saved as an integer. We therefore need to change the copd variable from an integer to a factor variable. We do this using the command <strong>factor()</strong></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(e<span class="sc">$</span>copd) <span class="co"># look at the variable category for copd tin the e  dataset</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "numeric"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a>e<span class="sc">$</span>copd <span class="ot">&lt;-</span> <span class="fu">factor</span>(e<span class="sc">$</span>copd) <span class="co"># convert copd to a factor variable</span></span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(e<span class="sc">$</span>copd) <span class="co"># look at the variable category for copd in the e dataset </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "factor"</code></pre>
</div>
</div>
<p>To visualise the structure of the data in that variable, you can use the str() function:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(e<span class="sc">$</span>copd) <span class="co"># List th structure of the data in the variable copd (in the e dataset)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Factor w/ 4 levels "1","2","3","4": 3 2 2 4 3 2 3 3 2 3 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(e<span class="sc">$</span>COPDSEVERITY)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> chr [1:101] "SEVERE" "MODERATE" "MODERATE" "VERY SEVERE" "SEVERE" ...</code></pre>
</div>
</div>
<p>Now, if you run your regression, you will get an output for three of the levels of the copd variable:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a>lr1<span class="ot">&lt;-</span> <span class="fu">lm</span>(e<span class="sc">$</span>MWT1Best<span class="sc">~</span>e<span class="sc">$</span>copd, <span class="at">data =</span> e) <span class="co"># Run linear regresion : MWT1Best = alfa + beta*copd</span></span>
<span id="cb100-2"><a href="#cb100-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lr1) <span class="co"># View th output of the regression</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = e$MWT1Best ~ e$copd, data = e)

Residuals:
    Min      1Q  Median      3Q     Max 
-248.67  -51.18    0.91   64.23  330.33 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   458.09      20.44  22.410  &lt; 2e-16 ***
e$copd2       -51.09      25.43  -2.009  0.04735 *  
e$copd3       -89.42      27.82  -3.215  0.00178 ** 
e$copd4      -167.21      40.24  -4.156 7.05e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 98.03 on 96 degrees of freedom
  (1 observation deleted due to missingness)
Multiple R-squared:  0.1792,    Adjusted R-squared:  0.1535 
F-statistic: 6.984 on 3 and 96 DF,  p-value: 0.0002671</code></pre>
</div>
</div>
<p><strong>NOTE:</strong> there are only coefficients for three of the levels because the coefficients represent the comparison with the fourth level, which is often referred to as the reference group.</p>
<ul>
<li>If you want to change a variable to a numeric data type, use the command <strong>as.numeric().</strong></li>
<li>If you want to change a variable to a character data type, use the command <strong>as.character().</strong></li>
<li>If you want to change a variable to a integer data type, use the command <strong>as.integer().</strong></li>
</ul>
<p><strong>Changing the reference category of a categorical variable</strong></p>
<ul>
<li>When running the above regression of walking distance on COPD severity, the linear regression model automatically uses COPD level 1 (i.e.&nbsp;‘mild’) as the reference category:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb102"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a>lr1<span class="ot">&lt;-</span> <span class="fu">lm</span>(e<span class="sc">$</span>MWT1Best<span class="sc">~</span>e<span class="sc">$</span>copd, <span class="at">data =</span> e) <span class="co"># Run linear regresion : MWT1Best = alfa + beta*copd</span></span>
<span id="cb102-2"><a href="#cb102-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lr1) <span class="co"># View th output of the regression</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = e$MWT1Best ~ e$copd, data = e)

Residuals:
    Min      1Q  Median      3Q     Max 
-248.67  -51.18    0.91   64.23  330.33 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   458.09      20.44  22.410  &lt; 2e-16 ***
e$copd2       -51.09      25.43  -2.009  0.04735 *  
e$copd3       -89.42      27.82  -3.215  0.00178 ** 
e$copd4      -167.21      40.24  -4.156 7.05e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 98.03 on 96 degrees of freedom
  (1 observation deleted due to missingness)
Multiple R-squared:  0.1792,    Adjusted R-squared:  0.1535 
F-statistic: 6.984 on 3 and 96 DF,  p-value: 0.0002671</code></pre>
</div>
</div>
<p>If you wanted to use the ‘severe’ group as a reference category for COPD severity (i.e.&nbsp;level 3), you can use the <strong>relevel()</strong> function:</p>
<p><strong>COPD</strong><span class="math inline">\(copd &lt;- relevel(COPD\)</span>copd, ref=3)</p>
<p>The output now becomes:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb104"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1" aria-hidden="true" tabindex="-1"></a>e<span class="sc">$</span>copd <span class="ot">&lt;-</span> <span class="fu">relevel</span>(e<span class="sc">$</span>copd, <span class="at">ref=</span><span class="dv">3</span>)</span>
<span id="cb104-2"><a href="#cb104-2" aria-hidden="true" tabindex="-1"></a>lr1<span class="ot">&lt;-</span> <span class="fu">lm</span>(e<span class="sc">$</span>MWT1Best<span class="sc">~</span>e<span class="sc">$</span>copd, <span class="at">data =</span> e) <span class="co"># Run linear regresion : MWT1Best = alfa + beta*copd</span></span>
<span id="cb104-3"><a href="#cb104-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lr1) <span class="co"># View th output of the regression</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = e$MWT1Best ~ e$copd, data = e)

Residuals:
    Min      1Q  Median      3Q     Max 
-248.67  -51.18    0.91   64.23  330.33 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   368.67      18.87  19.541  &lt; 2e-16 ***
e$copd1        89.42      27.82   3.215  0.00178 ** 
e$copd2        38.33      24.18   1.585  0.11620    
e$copd4       -77.79      39.46  -1.971  0.05157 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 98.03 on 96 degrees of freedom
  (1 observation deleted due to missingness)
Multiple R-squared:  0.1792,    Adjusted R-squared:  0.1535 
F-statistic: 6.984 on 3 and 96 DF,  p-value: 0.0002671</code></pre>
</div>
</div>
<p><strong>NOTE</strong>: this function only works with variables saved as factors!</p>
<p><strong>Create new variables from old ones</strong></p>
<p>You now want to create a new variable, which indicates the presence of at least one comorbidity or complete absence of comorbidities, based on the responses to the variables: Diabetes, muscular, hypertension, AtrialFib, and IHD.</p>
<p>Call this variable <strong>‘comorbid’.</strong></p>
<ul>
<li>Firstly, you need to make sure that the different variables are saved as the correct data type in R. All variables are binary variables, coded ‘1’ for positive and ‘0’ for negative. We therefore expect the variables to be correctly saved as factors.</li>
<li>If they are not, use the command factor() to convert them to that data type, as explained previously. Now, you need to create the vector comorbid. You will not have any data in it yet, as the data held in this vector is conditional on what is in other variables. However, you do know that you want it to be the same length as the other variables (i.e.&nbsp;101 values). To do this, you can use the following command:<br>
</li>
<li><strong>comorbid &lt;- length(COPD$Diabetes)</strong></li>
<li>Once you have created this vector, you can assign it the correct values. You want a binary vector (i.e.&nbsp;data type is factor in R) where 1 indicates the presence of at least one comorbidity and 0 represents the complete absence of comorbidities. So:</li>
<li>comorbid will have a value of 1 if Diabetes = 1, OR muscular = 1, OR hypertension = 1, OR AtrialFib = 1, OR IHD = 1.</li>
<li>comorbid will have a value of 0 if ALL of the above variables = 0.</li>
<li>Once you have assigned these values to the vector, you need to make sure it is saved as a factor variable.</li>
<li>Here is how you code for this in R:<br>
</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb106"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb106-1"><a href="#cb106-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(e<span class="sc">$</span>Diabetes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> num [1:101] 1 1 1 0 0 1 1 1 1 0 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb108"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb108-1"><a href="#cb108-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(e<span class="sc">$</span>muscular)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> num [1:101] 0 0 0 0 1 0 0 0 0 1 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb110"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb110-1"><a href="#cb110-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(e<span class="sc">$</span>hypertension)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> num [1:101] 0 0 0 1 1 0 0 0 0 0 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb112"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb112-1"><a href="#cb112-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(e<span class="sc">$</span>AtrialFib)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> num [1:101] 1 1 1 1 0 1 1 1 1 0 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb114"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb114-1"><a href="#cb114-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(e<span class="sc">$</span>IHD)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> num [1:101] 0 1 0 0 0 0 0 0 0 0 ...</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb116"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb116-1"><a href="#cb116-1" aria-hidden="true" tabindex="-1"></a>e<span class="sc">$</span>copd <span class="ot">&lt;-</span> <span class="fu">factor</span>(e<span class="sc">$</span>copd)</span>
<span id="cb116-2"><a href="#cb116-2" aria-hidden="true" tabindex="-1"></a>e<span class="sc">$</span>Diabetes <span class="ot">&lt;-</span> <span class="fu">factor</span>(e<span class="sc">$</span>Diabetes)</span>
<span id="cb116-3"><a href="#cb116-3" aria-hidden="true" tabindex="-1"></a>e<span class="sc">$</span>muscular <span class="ot">&lt;-</span> <span class="fu">factor</span>(e<span class="sc">$</span>muscular)</span>
<span id="cb116-4"><a href="#cb116-4" aria-hidden="true" tabindex="-1"></a>e<span class="sc">$</span>hypertension <span class="ot">&lt;-</span> <span class="fu">factor</span>(e<span class="sc">$</span>hypertension)</span>
<span id="cb116-5"><a href="#cb116-5" aria-hidden="true" tabindex="-1"></a>e<span class="sc">$</span>AtrialFib <span class="ot">&lt;-</span> <span class="fu">factor</span>(e<span class="sc">$</span>AtrialFib)</span>
<span id="cb116-6"><a href="#cb116-6" aria-hidden="true" tabindex="-1"></a>e<span class="sc">$</span>IHD <span class="ot">&lt;-</span> <span class="fu">factor</span>(e<span class="sc">$</span>IHD)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb117"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb117-1"><a href="#cb117-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(e<span class="sc">$</span>Diabetes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Factor w/ 2 levels "0","1": 2 2 2 1 1 2 2 2 2 1 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb119"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb119-1"><a href="#cb119-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(e<span class="sc">$</span>muscular)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Factor w/ 2 levels "0","1": 1 1 1 1 2 1 1 1 1 2 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb121"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb121-1"><a href="#cb121-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(e<span class="sc">$</span>hypertension)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Factor w/ 2 levels "0","1": 1 1 1 2 2 1 1 1 1 1 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb123"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb123-1"><a href="#cb123-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(e<span class="sc">$</span>AtrialFib)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Factor w/ 2 levels "0","1": 2 2 2 2 1 2 2 2 2 1 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb125"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb125-1"><a href="#cb125-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(e<span class="sc">$</span>IHD)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Factor w/ 2 levels "0","1": 1 2 1 1 1 1 1 1 1 1 ...</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb127"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb127-1"><a href="#cb127-1" aria-hidden="true" tabindex="-1"></a>comorbid <span class="ot">&lt;-</span> <span class="fu">length</span>(e<span class="sc">$</span>Diabetes) <span class="co"># create a new vector called "comorbid", of the Diabetes variable i.e 101.</span></span>
<span id="cb127-2"><a href="#cb127-2" aria-hidden="true" tabindex="-1"></a>comorbid[e<span class="sc">$</span>Diabetes <span class="sc">==</span> <span class="dv">1</span> <span class="sc">|</span> e<span class="sc">$</span>muscular <span class="sc">==</span> <span class="dv">1</span> <span class="sc">|</span> e<span class="sc">$</span>hypertension <span class="sc">==</span> <span class="dv">1</span> <span class="sc">|</span> e<span class="sc">$</span>AtrialFib  <span class="sc">==</span> <span class="dv">1</span> <span class="sc">|</span> e<span class="sc">$</span>IHD <span class="sc">==</span> <span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="dv">1</span> </span>
<span id="cb127-3"><a href="#cb127-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Assign a value of 1 in the comorbid vector if the variable Diabetes = 1 OR if the variable muscular = 1 OR if the variable Hypertension = 1 OR if the variable Atrialfib = 1 OR if the variable  IDH = 1</span></span>
<span id="cb127-4"><a href="#cb127-4" aria-hidden="true" tabindex="-1"></a>comorbid[<span class="fu">is.na</span>(comorbid)] <span class="ot">&lt;-</span> <span class="dv">0</span> <span class="co"># assign a value of 0 in the comorbid vector to the NA values in the vector</span></span>
<span id="cb127-5"><a href="#cb127-5" aria-hidden="true" tabindex="-1"></a>comorbid <span class="ot">&lt;-</span> <span class="fu">factor</span>(comorbid) <span class="co"># Convert comorbid a factor</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Once you have done this, there are different ways you can look at your data. You can:</p>
<ul>
<li>Look at all of the values contained in the vector by using the <strong>print()</strong> function</li>
<li>Look at the structure of your data in the vector using the <strong>str()</strong> function</li>
<li>Look at a specific value in your vector, for example the 15th value, specifying it using the <strong>[]</strong> symbols</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb128"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb128-1"><a href="#cb128-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(comorbid) <span class="co"># looks at the data in the vector comorbid</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1 0 0 0 0 0 0 1 0 0 0 1 1 1 0 1 1 0 0 0 1
 [38] 1 1 1 0 0 1 1 0 1 1 1 1 0 1 1 0 1 1 1 1 1 0 1 1 1 1 0 0 1 1 0 0 0 0 0 0 1
 [75] 0 0 0 0 1 0 1 1 0 0 1 0 0 1 0 0 0 0 0 0 1 1 1 1 1 0 0
Levels: 0 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb130"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb130-1"><a href="#cb130-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(comorbid) <span class="co"># look at the structure of the data in the vector comorbid</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Factor w/ 2 levels "0","1": 2 2 2 2 2 2 2 2 2 2 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb132"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb132-1"><a href="#cb132-1" aria-hidden="true" tabindex="-1"></a>comorbid[<span class="dv">15</span>] <span class="co"># look at the 15th value in the vector comorbid.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0
Levels: 0 1</code></pre>
</div>
</div>
<p>If you want to add this new variable to your existing dataset (COPD), you can do so using the following command:</p>
<p><strong>COPD$comorbid &lt;- comorbid</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb134"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb134-1"><a href="#cb134-1" aria-hidden="true" tabindex="-1"></a>e<span class="sc">$</span>comorbid <span class="ot">&lt;-</span> comorbid</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="good-practice-steps" class="level3" data-number="11.0.4">
<h3 data-number="11.0.4" class="anchored" data-anchor-id="good-practice-steps"><span class="header-section-number">11.0.4</span> Good Practice Steps</h3>
<p>Below are good practice steps you should go through before fitting a multivariable linear regression model.</p>
<p><strong>The good practice steps to develop a multivariable linear regression model are:</strong></p>
<ol type="1">
<li>Inspect your variables using summary statistics and histograms for continuous variables, and tabulations for categorical variables.</li>
</ol>
<p><em>This helps you identify and quantify the amount of missing information.</em> It also helps you spot any strange or outlying observations.<br>
If you do spot any strange values you will need to decide what to do with them before you move on.</p>
<ol start="2" type="1">
<li>Examine the relationship between your candidate predictor variables using cross tabulations for categorical variables and pairwise correlations and scatterplot matrices for continuous variables.</li>
</ol>
<p><em>This helps you identify potential associations in your candidate predictor variables that could be problematic if included together in your multivariable model.</em></p>
<ol start="3" type="1">
<li>Fit a simple linear regression model between the outcome and each of your candidate predictor variables.</li>
</ol>
<p><em>This allows you to assess the relationship between each of your candidate predictor variables and the outcome variable. Again, this helps to spot errors in either the data or the coding, and it also allows you to anticipate what you might expect to happen when you fit the multivariable model.</em></p>
<p>Once you’ve done this you’re in a much better position to start thinking about building a multivariable regression model.</p>
</section>
<section id="practice-with-r-run-a-good-practice-analysis" class="level3" data-number="11.0.5">
<h3 data-number="11.0.5" class="anchored" data-anchor-id="practice-with-r-run-a-good-practice-analysis"><span class="header-section-number">11.0.5</span> Practice with R: Run a Good Practice Analysis</h3>
<p>You have already learned how to fit a regression model in R and interpret the results for continuous and categorical variables.</p>
<p>You’ve also examined a few selected predictors but, in practice, there are often many candidate predictors. Decisions need to be made about whether variables are suitable to include, which of them to include, and how to include them for your analysis. If you have a lot of variables, it’s quite easy to get lost in a ‘forest of results’.</p>
<p>So, you are going to go through some <strong>good practice approaches</strong> that will help you to check your data and organise your analysis.</p>
<p>Working with the COPD_student dataset, which is a modest dataset with regards to the number of variables included, you’ll still have quite a lot to examine here. The different variables can be categorised as such:</p>
<p>$ The dataset contains variables on 4 patient characteristics: ‘age’; ‘gender’; ‘pack history’; and ‘smoking’.</p>
<p>There are two measures of disease severity: ‘COPD severity score’; and the variable ‘CAT’ which stands for COPD Assessment Test.</p>
<p>There are 4 measures of lung function; ‘FEV1’ which, as you know, is the amount of air a person can exhale in one second, whereas ‘FVC’ is the amount of air a person can exhale after taking a deep breath.</p>
<p>The two variables ‘FEV1PRED’ and ‘FVCPRED’ are the percentage of the predicted normal for a person of the same ‘gender’, ‘age’ and ‘height’.</p>
<p>Then there are also measures for ‘anxiety and depression’, ‘quality of life’ and the presence of comorbidities.</p>
<ol type="1">
<li>Inspect the dataset for missing values and outliers</li>
</ol>
<p>The first thing to do is to examine the datatype and distribution for all of these variables. This can be done using the describe() function from the ‘Hmisc’ package. This function allows you to examine the different variables, providing the number of values, the range of the values, the number of missing values, the mean, and the different quartiles of values in our variables.</p>
<p>After you’ve downloaded the package, you can type the command describe(COPD). This should be your output:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb135"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb135-1"><a href="#cb135-1" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages(Hmisc) </span></span>
<span id="cb135-2"><a href="#cb135-2" aria-hidden="true" tabindex="-1"></a><span class="co">#library(Hmisc) </span></span>
<span id="cb135-3"><a href="#cb135-3" aria-hidden="true" tabindex="-1"></a><span class="co">#describe(e)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>You may then want to examine each variable in more detail using summary statistics and tabulations. These allow you to spot missing data or outliers, which you might need to exclude for the next stages of your analysis.</p>
<p>For categorical variables, you can tabulate the data using the *CrossTable() <strong>function from the ‘gmodels’ package, then use the</strong> sum(is.na())** functions to check for missing values. In cases where there are none, you should query the investigator as to whether or not any participants with missing values have been excluded prior to getting the dataset. In this data set you would also ask about how the comorbidity data was collected.</p>
<p>So, for example, the output for the categorical variable copd is:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb136"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb136-1"><a href="#cb136-1" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages(gmodels) </span></span>
<span id="cb136-2"><a href="#cb136-2" aria-hidden="true" tabindex="-1"></a><span class="co">#library(gmodels) </span></span>
<span id="cb136-3"><a href="#cb136-3" aria-hidden="true" tabindex="-1"></a><span class="co">#CrossTable(e$copd)</span></span>
<span id="cb136-4"><a href="#cb136-4" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(e<span class="sc">$</span>copd))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<p>For continuous variables, such as MWT1Best, use the <strong>summary()</strong> command, which will allow you to look at the mean, median, minimum, maximum, 1st and 3rd quartiles, and the number of missing values (NAs):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb138"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb138-1"><a href="#cb138-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(e<span class="sc">$</span>MWT1Best)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
  120.0   303.8   420.0   399.1   465.2   699.0       1 </code></pre>
</div>
</div>
<p>A quick visual way to examine continuous variables is with a histogram using hist(), as you saw earlier in the course. You can use the plot to assess the distribution and identify any outliers. So, for example, using the AGE variable, you would get this output: <strong>hist(COPD$AGE)</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb140"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb140-1"><a href="#cb140-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(e<span class="sc">$</span>AGE) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Linear-Regression-in-R-for-Public-Health_files/figure-html/unnamed-chunk-42-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>If you do this for all the continuous variables in the dataset, you’ll find at least one variable that has an extreme value. So you’ll need to make a decision whether this value is an impossible value, maybe due to a coding error, in which case the value may need to be excluded, or whether you think this is it just an unusual value that should be left. In practice, if you saw a potential error, you would ask the researcher to go back to the original data and check, as part of the data cleaning prior to analysis.</p>
<p><strong>2. Examine the relationship between your candidate predictor variables</strong></p>
<p>When you are familiar with each variable, the next stage is to examine the relationship between predictors using correlations and tabulations. For continuous variables, we will be using pairwise correlations and scatterplot matrices, while we will be using cross tabulations for categorical variables. These will help you identify potential associations in your candidate predictor variables that could be problematic if included together in your multivariable model.</p>
<p>At the start of this course, you learned how to calculate a correlation coefficient using the cor.test() command. To see the pairwise correlation coefficient only for continuous variables, you can use the cor() command. The output of this command will be Pearson’s correlation coefficient by default. If you want Spearman’s correlation coefficient, you can specify this by adding method = ‘spearman’ in the cor() command parentheses.</p>
<p>So, for example, let’s say you want Pearson’s pairwise correlation coefficient for the variables AGE, PackHistory, FEV1, FEV1PRED, FVC, CAT, HAD, and SGRQ. You’ll need to create a correlation matrix to view all the different correlation coefficients. This can be done using the following code:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb141"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb141-1"><a href="#cb141-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Correlation Matrix</span></span>
<span id="cb141-2"><a href="#cb141-2" aria-hidden="true" tabindex="-1"></a>my_data <span class="ot">&lt;-</span> e[,<span class="fu">c</span>(<span class="st">"AGE"</span>, <span class="st">"PackHistory"</span>, <span class="st">"FEV1"</span>, <span class="st">"CAT"</span>, <span class="st">"HAD"</span>, <span class="st">"SGRQ"</span>)] <span class="co"># Create a new vector including the variables to be analysed</span></span>
<span id="cb141-3"><a href="#cb141-3" aria-hidden="true" tabindex="-1"></a>cor_matrix <span class="ot">&lt;-</span> <span class="fu">cor</span>(my_data) <span class="co"># create a correlation Matrix of the variable that are to be analysed.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>To view your output, you can use the following command(s):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb142"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb142-1"><a href="#cb142-1" aria-hidden="true" tabindex="-1"></a>cor_matrix<span class="co"># View the correlation Matrix</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                     AGE  PackHistory        FEV1         CAT         HAD
AGE          1.000000000 -0.001545507 -0.10212241  0.08336113 -0.22712040
PackHistory -0.001545507  1.000000000 -0.13150514 -0.14324773  0.02787635
FEV1        -0.102122406 -0.131505136  1.00000000 -0.06480429 -0.14814655
CAT          0.083361126 -0.143247732 -0.06480429  1.00000000  0.16191871
HAD         -0.227120404  0.027876353 -0.14814655  0.16191871  1.00000000
SGRQ        -0.139361205  0.032126419 -0.30340676  0.28778173  0.39579044
                   SGRQ
AGE         -0.13936121
PackHistory  0.03212642
FEV1        -0.30340676
CAT          0.28778173
HAD          0.39579044
SGRQ         1.00000000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb144"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb144-1"><a href="#cb144-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(cor_matrix,<span class="dv">2</span>) <span class="co"># Round the Values of the Correlation matrix to 2 Decimal points.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              AGE PackHistory  FEV1   CAT   HAD  SGRQ
AGE          1.00        0.00 -0.10  0.08 -0.23 -0.14
PackHistory  0.00        1.00 -0.13 -0.14  0.03  0.03
FEV1        -0.10       -0.13  1.00 -0.06 -0.15 -0.30
CAT          0.08       -0.14 -0.06  1.00  0.16  0.29
HAD         -0.23        0.03 -0.15  0.16  1.00  0.40
SGRQ        -0.14        0.03 -0.30  0.29  0.40  1.00</code></pre>
</div>
</div>
<p>There is an easy way to visually assess the correlation using the pairs() function. So, for the above correlation matrix, you would get:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb146"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb146-1"><a href="#cb146-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(<span class="sc">~</span> AGE <span class="sc">+</span> PackHistory <span class="sc">+</span> FEV1 <span class="sc">+</span> FEV1PRED <span class="sc">+</span> FVC <span class="sc">+</span> CAT <span class="sc">+</span> HAD <span class="sc">+</span> SGRQ, <span class="at">data =</span> e) <span class="co"># Comand to produce the correlation plot</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Linear-Regression-in-R-for-Public-Health_files/figure-html/unnamed-chunk-45-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>To examine associations between categorical variables, you can use cross tabulations. For this, you will again use the <strong>CrossTable()</strong> function from the ‘gmodels’ package, but adding your variables in the following format: <strong>CrossTable(mydata</strong><span class="math inline">\(myrowvar, mydata\)</span>mycolvar).</p>
<p>So, let’s say for example that you’d like to check whether the same people have ischemic heart disease (variable IHD) and hypertension:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb147"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb147-1"><a href="#cb147-1" aria-hidden="true" tabindex="-1"></a><span class="co">#CrossTable(e$hypertension, e$IHD)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This cross tabulation shows you that 8 patients had IHD only, and 11 patients had hypertension only, one person had both hypertension and IHD and 81 had neither. So, you would not be concerned if you wanted to include both of these in the model.</p>
<p><strong>3. Fit a simple linear regression model</strong></p>
<p>And finally, it’s useful to assess the relationship for each of variable in turn with the outcome. You can do this by fitting a regression model with just a single predictor in. Doing this allows an opportunity to spot anything unusual that may due to errors in either the data or coding of the variable, and also allows you to anticipate what you might expect to happen when you fit the multivariable model.</p>
<p>It may be at this stage you discover a relationship that, subsequently, disappears in the multiple model, or there may be no relationship at this stage but that one is uncovered later.</p>
<p>Recall that fitting a linear regression model uses the <strong>lm() function</strong> in the following format:</p>
<p><strong>model_name &lt;- lm(outcome ~ predictor, data =dataframe)</strong></p>
<p><strong>summary(model_name)</strong></p>
<p><strong>confint(model_name)</strong></p>
<p><strong>Summary</strong></p>
<p>MWT1Best_copdseverity &lt;- lm(e<span class="math inline">\(MWT1Best~e\)</span>COPDSEVERITY, datos = e) summary(MWT1Best_copdseverity) confint(MWT1Best_copdseverity) To summarise, it’s important that you get to know your data really well before you start modelling.</p>
<p>|Examine | Categorical | Continuos |…..:|:…..:|:…..:|:…….| |inspect variable | Tabulations | Summary statistics Histograms |Between Variables | Cross Tabulations | Pairwise correlations. Scatterplot Matrix. |With the outcome | Lin. Reg. with a variable | Lin. Reg, with Variable.</p>
<p>The first thing is examining variable distributions using summary statistics, tabulations and graphs.</p>
<p>The next stage is examining the relationship between candidate predictors using cross tabulations and correlations.</p>
<p>And finally, get a feel for the relationships between each of the candidate predictors and the outcome by fitting a regression model for each variable in turn.</p>
<p>This strategy will generate a fair amount of output for you to look through. My approach would be:</p>
<p>to set the statistical code up in advance run all the analyses then grab a coffee - take some time to look over and absorb the results.</p>
</section>
<section id="practice-with-r-run-multiple-regression" class="level3" data-number="11.0.6">
<h3 data-number="11.0.6" class="anchored" data-anchor-id="practice-with-r-run-multiple-regression"><span class="header-section-number">11.0.6</span> Practice with R: Run Multiple Regression</h3>
<p>Practice with R: Run Multiple Regression Having been through the good practice approach you should now be familiar with the variables in the COPD dataset. Hopefully, you are happy that there are no unusual or outlying observations in the dataset, and if there are, you should have thought about a strategy to deal with them. Imagine that you have selected lung function (FEV1), age (AGE), gender (gender), COPD severity (COPDSEVERITY) and presence of any comorbidity (comorbid) as the final predictor variables for your multivariable model. Don’t forget that MWT1best is your outcome variable.</p>
<p>Try fitting this multivariable model yourself in R: What do you find?</p>
<p>What do the coefficients tell you about the relationships between the predictor variables and your outcome?</p>
<p>Consider these further questions: How do the coefficients and adjusted R2 compare with the bivariate models you fitted in Good practice steps in R?</p>
<p>Does anything unexpected appear to be happening to the values of the coefficients now they are included in the model with multiple other predictors? How could you assess this?</p>
<p>Are there any other steps you should take?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb148"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb148-1"><a href="#cb148-1" aria-hidden="true" tabindex="-1"></a><span class="co">#MWT1Best_Multivar &lt;- lm(e$MWT1Best~ e$FEV1, e$AGE, e$gender, e$COPDSEVERITY, e$comorbid,  data = e)??????? No Localizo el error, checarlo..</span></span>
<span id="cb148-2"><a href="#cb148-2" aria-hidden="true" tabindex="-1"></a><span class="co">#summary(MWT1Best_copdseverity) </span></span>
<span id="cb148-3"><a href="#cb148-3" aria-hidden="true" tabindex="-1"></a><span class="co">#confint(MWT1Best_copdseverity)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="feedback-practice-with-r-run-multiple-regression" class="level3" data-number="11.0.7">
<h3 data-number="11.0.7" class="anchored" data-anchor-id="feedback-practice-with-r-run-multiple-regression"><span class="header-section-number">11.0.7</span> Feedback Practice with R: Run Multiple Regression</h3>
<p><strong>You might be happy to skip over this feedback if you feel you have fully understood and been able to undertake all the good practice steps. If so, skip on to the feedback at the bottom of this section.</strong></p>
<p>In the previous items, you should have gone through the <strong>good practice steps</strong> to better understand the COPD dataset.</p>
<p><strong>Step 1</strong></p>
<p>Examine each variable in turn, so that you’re familiar with all of the variables in your dataset. Recall the R code for this is:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb149"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb149-1"><a href="#cb149-1" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages(Hmisc) # Dawload the HMIsc package </span></span>
<span id="cb149-2"><a href="#cb149-2" aria-hidden="true" tabindex="-1"></a><span class="co">#library(Hmisc) # load the lbrary</span></span>
<span id="cb149-3"><a href="#cb149-3" aria-hidden="true" tabindex="-1"></a><span class="co">#describe(e)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Summary statistics will give you a little more detail and might help you spot any outliers.</p>
<p>The categorical variables are: copd, gender, smoking and comorbid.</p>
<p>To check whether these are correctly registered as categorical variables, use the class() function. If they are not, you can recode them as factor variables using the <strong>factor() function</strong>. Recall the R code for this is:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb150"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb150-1"><a href="#cb150-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(e<span class="sc">$</span>gender)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "factor"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb152"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb152-1"><a href="#cb152-1" aria-hidden="true" tabindex="-1"></a>e<span class="sc">$</span>gender <span class="ot">&lt;-</span> <span class="fu">factor</span>(e<span class="sc">$</span>gender)</span>
<span id="cb152-2"><a href="#cb152-2" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(e<span class="sc">$</span>gender)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "factor"</code></pre>
</div>
</div>
<p>You can now look at your categorical variables using the <strong>describe()</strong> function</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb154"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb154-1"><a href="#cb154-1" aria-hidden="true" tabindex="-1"></a><span class="co">#describe(e$gender)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Or you can now look at your categorical variables using the <strong>CrossTable() and sum()</strong> functions, from the ‘gmodels’ package (you need to load this before you can run the command).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb155"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb155-1"><a href="#cb155-1" aria-hidden="true" tabindex="-1"></a><span class="co">#CrossTable(e$gender)</span></span>
<span id="cb155-2"><a href="#cb155-2" aria-hidden="true" tabindex="-1"></a><span class="co">#sum(is.na(e$gender))</span></span>
<span id="cb155-3"><a href="#cb155-3" aria-hidden="true" tabindex="-1"></a><span class="co">#sum(is.na(g$dm))</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The continuous variables are: AGE, PackHistory, CAT, FEV1, FEV1PRED, FVC, FVCPRED, HAD, SGRQ. The R code for summary statistics and histograms is:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb156"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb156-1"><a href="#cb156-1" aria-hidden="true" tabindex="-1"></a><span class="co">#histograms</span></span>
<span id="cb156-2"><a href="#cb156-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(e<span class="sc">$</span>AGE, <span class="at">main=</span> <span class="st">"Histograma de Edad"</span>, <span class="at">xlab=</span> <span class="st">"EDAD"</span>) <span class="co"># Histogram of age, with title "Historgrama de Edad " and x axis label "Edad"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Linear-Regression-in-R-for-Public-Health_files/figure-html/unnamed-chunk-53-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb157"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb157-1"><a href="#cb157-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(e<span class="sc">$</span>PackHistory)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Linear-Regression-in-R-for-Public-Health_files/figure-html/unnamed-chunk-53-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb158"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb158-1"><a href="#cb158-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(e<span class="sc">$</span>CAT)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Linear-Regression-in-R-for-Public-Health_files/figure-html/unnamed-chunk-53-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Did you spot anything strange in your data when you performed these steps?</p>
<p>Let’s look at the histogram for the COPD assessment test (CAT) predictor variable.</p>
</section>
</section>
<section id="week-4" class="level1" data-number="12">
<h1 data-number="12"><span class="header-section-number">12</span> WEEk 4</h1>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../files/c5-r.html" class="pagination-link" aria-label="R">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">R</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../files/c1-bash.html" class="pagination-link" aria-label="Bash">
        <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Bash</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>